name: Update version.txt with current date

on:
  push:
    branches:
      - main  # tukar ke nama branch kamu jika lain

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update version.txt
        run: |
          date +%Y%m%d > version.txt

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add version.txt
          git commit -m "Update version.txt to current date" || echo "No changes to commit"
          git push
